# Which interfaces to run:
interfaces:
  voice_remote: true
  voice_local: false
  web: true
  asterisk: true

ollama:
  host: "http://localhost:11434"
  model: "qwen3.5:9b"
  model_type: "qwen3"   # drives message formatting: "gemma", "qwen3" etc.

server:
  remote_voice_host: "0.0.0.0"
  remote_voice_port: 10400

# asterisk phone link - for phone connection to voice agent
asterisk:
  ari_host: "127.0.0.1"        # leave as-is (Asterisk is local)
  ari_port: 8088               # leave as-is unless you changed http.conf
  ari_user: "supernova"        # must match [supernova] section name in ari.conf
  ari_password: "supernovaaccess" # must match password in ari.conf - yes this is a password set in github, but access is restricted in asterisk to localhost connections only so it's low risk
  rtp_local_ip: "127.0.0.1"   # leave as-is (RTP stays local on Jetson)

# this section is so you can debug and take recordings on voice inputs for enrolling voices etc
debug:                        
  record_audio: false
  record_dir: "./debug_audio"

voice:
  model_path: "./libs/voices/glados_piper_medium.onnx"
  use_cuda: false

speaker_id:
  threshold: 0.5  # threshold to pass for positive speaker ID (only for Asterisk interface as it struggles with bad phone audio)