# Which interfaces to run:
interfaces:
  voice_remote: true
  voice_local: false
  web: true
  asterisk: true

ollama:
  host: "http://localhost:11434"
  model: "qwen3.5:4b"
  model_type: "qwen3"   # drives message formatting: "gemma", "qwen3" etc.

server:
  remote_voice_host: "0.0.0.0"
  remote_voice_port: 10400

home_assistant:
  url: "http://192.168.20.3:8123/api"

ptv:
  # From opendata.transport.vic.gov.au (create your own login):
  api_key: ""
  stop_id: "14312"           # Anstey Station platform 1 (citybound)
  stop_name: "Anstey Station"
  direction: "citybound"
  gtfs_zip_folder: "2"       # folder 2 = non-metro/regional in the GTFS zip
  # cache_file auto-set to config/ptv_cache.json if omitted
  walk_minutes: 7         # used in prompt formatting to give user an idea of how long to get to station before next train

# web search - configure to where you host searxng:
searxng:
  url: "http://localhost:8888"

# asterisk phone link - for phone connection to voice agent
asterisk:
  ari_host: "127.0.0.1"        # leave as-is (Asterisk is local)
  ari_port: 8088               # leave as-is unless you changed http.conf
  ari_user: "supernova"        # must match [supernova] section name in ari.conf
  ari_password: "supernovaaccess" # must match password in ari.conf - yes this is a password set in github, but access is restricted in asterisk to localhost connections only so it's low risk
  rtp_local_ip: "127.0.0.1"   # leave as-is (RTP stays local on Jetson)